function createtextbox(figure1)
%CREATETEXTBOX(figure1)
%  FIGURE1:  annotation figure

%  Auto-generated by MATLAB on 03-Apr-2020 09:46:19

% Create textbox
annotation(figure1,'textbox',...
    [0.066625 0.390728476821192 0.0229583333333333 0.246688741721854],...
    'String',{'ccccccccccccc'},...
    'FitBoxToText','off', 'rotation', 90));

